name: real_time_video_sdk
description: "A production-ready Flutter video calling application with Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.1.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
